import base64
from os.path import join, dirname

from utils import generate_totp_qrcode, get_current_totp, secret_from_qrcode

if __name__ == "__main__":
    IMAGE_DIR = join(dirname(__file__), "..", "assets/test_images")

    SECRET = "never gonna give you up"
    secret = base64.b32encode(SECRET.encode()).decode().replace("=", "")

    # generate and save to file
    generate_totp_qrcode(SECRET, output=join(IMAGE_DIR, "output.png"))

    # get original totp straight from var
    print("Original Straight From Key:", get_current_totp(SECRET))

    # extract secret from qrcode (generated by line 64)
    secret1 = secret_from_qrcode(join(IMAGE_DIR, "qrcode.png"))
    print("From Image 1:", get_current_totp(secret1, encode=False))

    # try getting secret from qrcode from side angle
    secret2 = secret_from_qrcode(join(IMAGE_DIR, "side_angle.JPG"))
    print("From Image 2:", get_current_totp(secret2, encode=False))

    # make sure all that shit worked
    print("SECRETS:", secret, secret1, secret2)
    assert secret == secret == secret1

    assert (
        get_current_totp(secret, encode=False)
        == get_current_totp(secret1, encode=False)
        == get_current_totp(SECRET)
    )
